import { LibSQLDatabase } from 'drizzle-orm/libsql'
import * as schema from '@/db/schema'
import { Context } from 'hono'
import type { SecureHeadersVariables } from 'hono/secure-headers'
import { Client } from '@libsql/client/web'

/* type your Hono variables (used with c.get/c.set) here */
type Variables = SecureHeadersVariables & {
  db: LibSQLDatabase<typeof schema> & {
    $client: Client
  }
}

/* The "Env" is generated by Cloudflare Wrangler and is typed inside worder-configuration.d.ts */
export type ContextEnv = {
  Bindings: Required<Env> & { NODE_ENV: string }
  Variables: Variables
}

export function getLoadContext(c: Context<ContextEnv>) {
  const cloudflare = {
    cf: c.req.raw.cf,
    ctx: { ...c.executionCtx },
    caches: globalThis.caches ? caches : undefined,
    env: {
      ...c.env,
      NODE_ENV: process.env.NODE_ENV,
    },
  }

  return {
    cloudflare,
    nonce: c.get('secureHeadersNonce'),
  }
}

declare module '@remix-run/cloudflare' {
  interface AppLoadContext extends ReturnType<typeof getLoadContext> {
    db: Variables['db']
  }
}
