// Generated by Wrangler by running `wrangler types`

interface Env {
  KV: KVNamespace
  MY_VAR: 'XYZCloudflare'
  ALLOW_INDEXING: 'true'
  PROJECT_URL: 'http://localhost:3000'
  DATABASE_URL: string
  SESSION_SECRET: string
  HONEYPOT_SECRET: string
  INTERNAL_COMMAND_TOKEN: string
  GITHUB_CLIENT_ID: string
  GITHUB_CLIENT_SECRET: string
  GITHUB_TOKEN: string
  RESEND_API_KEY: string
  RESEND_EMAIL_FROM: string
  OPENAI_API_KEY: string
  ADMIN_USER_EMAIL: string
  ADMIN_USER_PASSWORD: string
  ASSETS: Fetcher
}
