// Generated by Wrangler by running `wrangler types`

interface Env {
	ALLOW_INDEXING: false;
	RESEND_EMAIL_FROM: "Gingga <notifications@gingga.com>";
	SENTRY_ORG: "gingga";
	SENTRY_PROJECT: "javascript";
	SENTRY_DSN: "https://b01eb5a3ef515103021d9b49ec52a161@o4508219743207424.ingest.de.sentry.io/4508219751727184";
	SENTRY_ENABLED_IN_DEV: false;
	DEV_APP_URL: "http://localhost:3000";
	PROD_APP_URL: "https://gingga.com";
	TURSO_DB_URL: string;
	TURSO_LOCAL_DB_URL: string;
	TURSO_AUTH_TOKEN: string;
	TURSO_API_TOKEN: string;
	SESSION_SECRET: string;
	HONEYPOT_SECRET: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GITHUB_TOKEN: string;
	RESEND_API_KEY: string;
	OPENAI_API_KEY: string;
	OPENROUTER_API_KEY: string;
	ADMIN_USER_EMAIL: string;
	ADMIN_USER_PASSWORD: string;
	SENTRY_AUTH_TOKEN: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	GH_TOKEN: string;
	CLOUDFLARE_TURNSTILE_SITE_KEY: string;
	CLOUDFLARE_TURNSTILE_SECRET: string;
}
