name: Clean up Preview Deployment
on:
  pull_request:
    types: [closed]

env:
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get git branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Delete Turso Branch
        run: |
          curl -X DELETE \
          "https://api.turso.tech/v1/organizations/${{ secrets.TURSO_ORGANIZATION_NAME }}/databases/preview-${{ steps.branch-name.outputs.current_branch }}" \
          -H "Authorization: Bearer ${{ secrets.TURSO_AUTH_TOKEN }}"
