name: Preview Deployment
on: [pull_request]

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    name: Deploy Preview

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Get git branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Create Turso Database Branch
        id: create-db
        run: |
          RESPONSE=$(curl -X POST \
          -H "Authorization: Bearer ${{ secrets.TURSO_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"name": "preview-${{ github.sha }}", "group": "default", "seed": {"type": "database", "name": "${{ secrets.TURSO_DATABASE_NAME }}"} }' \
          "https://api.turso.tech/v1/organizations/${{ secrets.TURSO_ORGANIZATION_NAME }}/databases")

          if [ $? -ne 0 ]; then
            echo "API call failed"
            exit 1
          fi

          HOSTNAME=$(echo $RESPONSE | jq -r '.database.Hostname')
          if [ -z "$HOSTNAME" ]; then
            echo "Hostname not found in response"
            exit 1
          fi

          echo "hostname=$HOSTNAME" >> $GITHUB_ENV

      - name: Build
        run: pnpm run build
        env:
          TURSO_DB_URL: ${{ env.hostname }}

      - name: Run Migrations
        run: pnpm run db:migrate
        env:
          TURSO_DB_URL: ${{ env.hostname }}

      - name: Deploy to Workers Preview
        uses: cloudflare/wrangler-action@v3
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env preview
          environment: preview
          secrets: |
            TURSO_DB_URL
        env:
          TURSO_DB_URL: ${{ env.hostname }}

      - name: Extract Version ID
        id: version
        run: |
          VERSION_ID=$(echo '${{ steps.deploy.outputs.command-output }}' | grep "Current Version ID:" | cut -d' ' -f4 | cut -d'-' -f1)
          echo "version_id=$VERSION_ID" >> $GITHUB_OUTPUT

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
          message: |
            🚀 Preview deployment is ready!

            Worker Preview URL: https://${{ steps.version.outputs.version_id }}-gingga-preview.jsegoviadev.workers.dev
            Turso Database Branch: https://app.turso.tech/${{ secrets.TURSO_ORGANIZATION_NAME }}/databases/preview-${{ steps.branch-name.outputs.current_branch }}
